"""WireGuard configuration generator and onboarding script builder."""

from __future__ import annotations

from models.node import ComputeNode, GatewayNode
from models.topology import HomelabTopology


def generate_node_wg_conf(
    node_name: str,
    node: ComputeNode,
    gateway: GatewayNode,
    topology: HomelabTopology,
    private_key_placeholder: str = "$NODE_PRIVKEY",
) -> str:
    """Generate the /etc/wireguard/wg0.conf content for a compute node."""
    lines = [
        "# ==============================================================================",
        f"# WireGuard Backbone Configuration for Node: {node_name}",
        f"# Assigned Backbone IP: {node.backbone_ip}/24",
        "# Managed by Pluribus Homelab Engine",
        "# ==============================================================================",
        "",
        "[Interface]",
        f"Address = {node.backbone_ip}/24",
        f"PrivateKey = {private_key_placeholder}",
        f"MTU = {topology.mesh.mtu}",
        "",
        "[Peer]",
        f"# Ingress Gateway: {gateway.public_ip}:{topology.mesh.port}",
        f"PublicKey = {gateway.public_key}",
        f"Endpoint = {gateway.public_ip}:{topology.mesh.port}",
        f"AllowedIPs = {topology.mesh.subnet}",
        f"PersistentKeepalive = {topology.mesh.keepalive}",
        "",
    ]
    return "\n".join(lines)


def generate_gateway_wg_conf(
    gateway_name: str,
    gateway: GatewayNode,
    topology: HomelabTopology,
    private_key_placeholder: str = "$PRIVATE_KEY",
) -> str:
    """Generate the /etc/wireguard/wg0.conf content for an ingress gateway."""
    lines = [
        "# ==============================================================================",
        f"# WireGuard Backbone Configuration for Gateway: {gateway_name}",
        f"# Backbone IP: {gateway.backbone_ip}/24",
        "# Managed by Pluribus Homelab Engine",
        "# ==============================================================================",
        "",
        "[Interface]",
        f"Address = {gateway.backbone_ip}/24",
        f"ListenPort = {topology.mesh.port}",
        f"PrivateKey = {private_key_placeholder}",
        "SaveConfig = false",
        "",
    ]

    for node_name, node in topology.nodes.items():
        lines.extend(
            [
                f"# Node: {node_name} ({node.role})",
                "[Peer]",
                f"PublicKey = {node.public_key}",
                f"AllowedIPs = {node.backbone_ip}/32",
                "",
            ]
        )

    return "\n".join(lines)


def generate_node_connect_script(
    node_name: str,
    topology: HomelabTopology,
) -> str:
    """Generate a self-contained, idempotent bash script to onboard/reconnect a node."""
    if node_name not in topology.nodes:
        raise ValueError(
            f"Node '{node_name}' not found. Available nodes: {list(topology.nodes.keys())}"
        )

    node = topology.nodes[node_name]
    gw_name = node.ssh.bastion or next(iter(topology.gateways.keys()))
    gateway = topology.gateways[gw_name]

    wg_conf_body = generate_node_wg_conf(
        node_name=node_name,
        node=node,
        gateway=gateway,
        topology=topology,
        private_key_placeholder="$NODE_PRIVKEY",
    )

    script = f"""#!/bin/bash
set -euo pipefail

# ==============================================================================
# WireGuard Backbone Connector for {node_name} ({node.backbone_ip}/24)
# Gateway: {gateway.public_ip}:{topology.mesh.port} ({gateway.backbone_ip})
# Generated by Pluribus Homelab Engine
# ==============================================================================

if [ "$EUID" -ne 0 ]; then
    echo "Error: Please run as root (cat << 'EOF' | sudo bash)" >&2
    exit 1
fi

echo ">>> [1/5] Ensuring WireGuard packages..."
if ! command -v wg >/dev/null 2>&1 || ! command -v wg-quick >/dev/null 2>&1; then
    echo "Installing wireguard tools..."
    apt-get update -qq
    apt-get install -y -qq wireguard wireguard-tools resolvconf
fi

echo ">>> [2/5] Configuring WireGuard keys in /etc/wireguard/..."
mkdir -p /etc/wireguard
chmod 700 /etc/wireguard

if [ -f /etc/wireguard/wg0.conf ] && grep -q "PrivateKey" /etc/wireguard/wg0.conf; then
    echo "Reusing existing PrivateKey from /etc/wireguard/wg0.conf..."
    NODE_PRIVKEY=$(sed -n "s/^[[:space:]]*PrivateKey[[:space:]]*=[[:space:]]*//p" /etc/wireguard/wg0.conf | tr -d "[:space:]")
    echo "$NODE_PRIVKEY" > /etc/wireguard/privatekey
    chmod 600 /etc/wireguard/privatekey
    echo "$NODE_PRIVKEY" | wg pubkey | tr -d "[:space:]" > /etc/wireguard/publickey
elif [ -f /etc/wireguard/privatekey ]; then
    echo "Reusing existing /etc/wireguard/privatekey..."
    NODE_PRIVKEY=$(cat /etc/wireguard/privatekey | tr -d "[:space:]")
    echo "$NODE_PRIVKEY" | wg pubkey | tr -d "[:space:]" > /etc/wireguard/publickey
else
    echo "Generating new WireGuard keypair..."
    umask 077
    NODE_PRIVKEY=$(wg genkey)
    echo "$NODE_PRIVKEY" | tee /etc/wireguard/privatekey | wg pubkey > /etc/wireguard/publickey
fi
chmod 600 /etc/wireguard/privatekey
chmod 644 /etc/wireguard/publickey
NODE_PUBKEY=$(cat /etc/wireguard/publickey)

echo ">>> [3/5] Writing /etc/wireguard/wg0.conf..."
cat <<CONFIG > /etc/wireguard/wg0.conf
{wg_conf_body}
CONFIG
chmod 600 /etc/wireguard/wg0.conf

echo ">>> [4/5] Enabling and restarting wg-quick@wg0..."
systemctl stop wg-quick@wg0 2>/dev/null || true
systemctl enable wg-quick@wg0
systemctl restart wg-quick@wg0

echo ">>> [5/5] Verifying WireGuard backbone status..."
echo "=================================================="
echo "Node            : {node_name}"
echo "Backbone IP     : {node.backbone_ip}"
echo "Node Public Key : $NODE_PUBKEY"
echo "=================================================="
wg show
echo "=================================================="
echo "Testing Ping to Gateway ({gateway.backbone_ip})..."
if ping -c 3 -W 3 "{gateway.backbone_ip}"; then
    echo "[SUCCESS] WireGuard backbone connected and reachable!"
else
    echo "[WARN] Ping failed. Ensure Gateway has registered public key: $NODE_PUBKEY"
fi
"""
    return script
