# Home Assistant Core Configuration
default_config:

# Standard includes for the UI-managed config files
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Reverse Proxy Configuration (Traefik)
# Required to allow logins via your public domain
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.10.0.1 # WireGuard Gateway IP (aperio)
    - 127.0.0.1
    - ::1

# Debug logging for troubleshooting
logger:
  default: warning
  logs:
    custom_components.openid: debug
    homeassistant.components.tapo: debug
