services:
  directus:
    image: directus/directus:latest
    container_name: lxb-directus-local
    ports:
      - "8055:8055"
    environment:
      KEY: "super_secret_test"
      SECRET: "super_secret_test"
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "admin"
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"
      WEBSOCKETS_ENABLED: "true"
      CORS_ENABLED: "true"
      CORS_ORIGIN: "true"
    volumes:
      - ./directus/data:/directus/database
      - ./directus/uploads:/directus/uploads
      - ./directus/extensions:/directus/extensions
