#!/bin/bash
set -euo pipefail

# ==============================================================================
# Pluribus Homelab: Node Backbone WireGuard Connector Generator
# projects/homelab/nodes/connector.sh
# ==============================================================================

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd -- "$SCRIPT_DIR/.." && pwd)"

# Load .env if present
if [ -f "$PROJECT_ROOT/.env" ]; then
    set -a
    # shellcheck disable=SC1090
    . "$PROJECT_ROOT/.env"
    set +a
fi

# Resolve Gateway and Backbone parameters
APERIO_IP="${APERIO_PUBLIC_IP:-${GATEWAY_PUBLIC_IP:-}}"
APERIO_WG_PORT="${BACKBONE_PORT:-51820}"
APERIO_BACKBONE_IP="${BACKBONE_APERIO_IP:-${BACKBONE_GATEWAY_IP:-10.10.0.1}}"
APERIO_PUBKEY="${BACKBONE_APERIO_PUBLIC_KEY:-${BACKBONE_GATEWAY_PUBLIC_KEY:-}}"

TARGET_NODE="${1:-macerator}"
TARGET_IP="${2:-}"

if [ -z "$TARGET_IP" ]; then
    case "$TARGET_NODE" in
        macerator|powerhouse)
            TARGET_IP="${BACKBONE_MACERATOR_IP:-${BACKBONE_POWERHOUSE_IP:-10.10.0.2}}"
            ;;
        *)
            TARGET_IP="10.10.0.10"
            ;;
    esac
fi

if [ -z "$APERIO_IP" ]; then
    echo "Error: APERIO_PUBLIC_IP or GATEWAY_PUBLIC_IP must be set in $PROJECT_ROOT/.env" >&2
    exit 1
fi

if [ -z "$APERIO_PUBKEY" ]; then
    echo "Error: BACKBONE_APERIO_PUBLIC_KEY is not defined in $PROJECT_ROOT/.env" >&2
    echo "Hint: You can obtain it from Aperio via: just ssh-aperio 'sudo cat /etc/wireguard/publickey'" >&2
    exit 1
fi

# Target script path
NODE_DIR="$SCRIPT_DIR/$TARGET_NODE"
mkdir -p "$NODE_DIR"
CONNECT_SCRIPT="$NODE_DIR/connect.sh"

# Generate the standalone node connect script
cat <<EOF > "$CONNECT_SCRIPT"
#!/bin/bash
set -euo pipefail

# ==============================================================================
# WireGuard Backbone Connector for $TARGET_NODE ($TARGET_IP/24)
# Gateway: $APERIO_IP:$APERIO_WG_PORT ($APERIO_BACKBONE_IP)
# Generated by Pluribus: nodes/connector.sh
# ==============================================================================

if [ "\$EUID" -ne 0 ]; then
    echo "Error: Please run as root (sudo bash \$0)" >&2
    exit 1
fi

echo ">>> [1/5] Ensuring WireGuard packages..."
if ! command -v wg >/dev/null 2>&1 || ! command -v wg-quick >/dev/null 2>&1; then
    echo "Installing wireguard tools..."
    apt-get update -qq
    apt-get install -y -qq wireguard wireguard-tools resolvconf
fi

echo ">>> [2/5] Configuring WireGuard keys in /etc/wireguard/..."
mkdir -p /etc/wireguard
chmod 700 /etc/wireguard

if [ -f /etc/wireguard/wg0.conf ] && grep -q "PrivateKey" /etc/wireguard/wg0.conf; then
    echo "Reusing existing PrivateKey from /etc/wireguard/wg0.conf..."
    NODE_PRIVKEY=\$(sed -n "s/^[[:space:]]*PrivateKey[[:space:]]*=[[:space:]]*//p" /etc/wireguard/wg0.conf | tr -d "[:space:]")
    echo "\$NODE_PRIVKEY" > /etc/wireguard/privatekey
    chmod 600 /etc/wireguard/privatekey
    echo "\$NODE_PRIVKEY" | wg pubkey | tr -d "[:space:]" > /etc/wireguard/publickey
elif [ -f /etc/wireguard/privatekey ]; then
    echo "Reusing existing /etc/wireguard/privatekey..."
    NODE_PRIVKEY=\$(cat /etc/wireguard/privatekey | tr -d "[:space:]")
    echo "\$NODE_PRIVKEY" | wg pubkey | tr -d "[:space:]" > /etc/wireguard/publickey
else
    echo "Generating new WireGuard keypair..."
    umask 077
    NODE_PRIVKEY=\$(wg genkey)
    echo "\$NODE_PRIVKEY" | tee /etc/wireguard/privatekey | wg pubkey > /etc/wireguard/publickey
fi
chmod 600 /etc/wireguard/privatekey
chmod 644 /etc/wireguard/publickey
NODE_PUBKEY=\$(cat /etc/wireguard/publickey)

echo ">>> [3/5] Writing /etc/wireguard/wg0.conf..."
cat <<CONFIG > /etc/wireguard/wg0.conf
[Interface]
Address = $TARGET_IP/24
PrivateKey = \$NODE_PRIVKEY
MTU = 1420

[Peer]
# Aperio Public Gateway
PublicKey = $APERIO_PUBKEY
Endpoint = $APERIO_IP:$APERIO_WG_PORT
AllowedIPs = 10.10.0.0/24
PersistentKeepalive = 25
CONFIG
chmod 600 /etc/wireguard/wg0.conf

echo ">>> [4/5] Enabling and restarting wg-quick@wg0..."
systemctl stop wg-quick@wg0 2>/dev/null || true
systemctl enable wg-quick@wg0
systemctl restart wg-quick@wg0

echo ">>> [5/5] Verifying WireGuard backbone status..."
echo "=================================================="
echo "Node            : $TARGET_NODE"
echo "Backbone IP     : $TARGET_IP"
echo "Node Public Key : \$NODE_PUBKEY"
echo "=================================================="
wg show
echo "=================================================="
echo "Testing Ping to Aperio Gateway ($APERIO_BACKBONE_IP)..."
if ping -c 3 -W 3 "$APERIO_BACKBONE_IP"; then
    echo "[SUCCESS] WireGuard backbone connected and reachable!"
else
    echo "[WARN] Ping failed. Ensure Aperio has registered public key: \$NODE_PUBKEY"
fi
EOF

chmod +x "$CONNECT_SCRIPT"

# Verify generated script syntax
if ! bash -n "$CONNECT_SCRIPT"; then
    echo "Error: Generated script failed syntax verification!" >&2
    exit 1
fi

echo "=============================================================================="
echo " WireGuard Backbone Connector Generated Successfully"
echo " Target Node : $TARGET_NODE"
echo " Assigned IP : $TARGET_IP/24"
echo " Gateway     : $APERIO_IP:$APERIO_WG_PORT ($APERIO_BACKBONE_IP)"
echo " Saved File  : projects/homelab/nodes/$TARGET_NODE/connect.sh"
echo "=============================================================================="
echo ""
echo "To connect $TARGET_NODE, run the following command directly on $TARGET_NODE:"
echo ""
echo "cat << 'EOF' | sudo bash"
cat "$CONNECT_SCRIPT"
echo "EOF"
echo ""
